[package]
name = "t-cli"
version = "0.4.1"
edition = "2021"

authors = ["Bay"]
description = "A simple CLI task manager"
repository = "https://github.com/zX3no/t"
readme = "README.md"
license = "CC0-1.0"

[profile.release]
panic = "abort"

[[bin]]
name = "t"
path = "src/main.rs"