[package]
name = "t-cli"
version = "0.1.1"
authors = ["Bay"]
description = "A simple CLI task manager"
edition = "2018"
repository = "https://github.com/zX3no/t"
readme = "README.md"
license = "MIT"

[profile.release]
debug = true

[[bin]]
name = "t"
path = "src/main.rs"

[dependencies]
toml = "0.5"
crossterm = "0.20"
serde = { version = "1.0", features = ["derive"] }
dirs = "3.0.2"
itertools = "0.10.1"
hashbrown = "0.11.2"
chrono = "0.4.19"
