[package]
name = "t-cli"
version = "0.3.1"
authors = ["Bay"]
description = "A simple CLI task manager"
edition = "2021"
repository = "https://github.com/zX3no/t"
readme = "README.md"
license = "MIT"

[[bin]]
name = "t"
path = "src/main.rs"

[dependencies]
crossterm = "0.22.1"
dirs = "4.0.0"
regex = "1.5.4"
lazy_static = "1.4.0"
rusqlite = { version = "0.26.3", features = ["bundled"] }
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
chrono = "0.4.19"
